// The hand-off decision under every policy, and the safety rules around it:
// nothing happens when the feature is off, warn reports without writing, sync
// writes only managed state and only when safe, strict refuses what it
// cannot make safe, a hand-edited file is backed up and left alone, a second
// sync writes nothing, a source change is noticed, ownership pruning never
// touches a real directory, the reverse direction works, and disabling
// removes nothing. All against throwaway homes.
import { test } from 'node:test'
import assert from 'node:assert/strict'
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync, lstatSync } from 'node:fs'
import { join } from 'node:path'
import { makeHome } from './helpers.mjs'
import { buildClaudeHome, buildCodexHome, buildAgyHome, CANARY, fakeToken } from './harness-fixture.mjs'

const HOME0 = makeHome()
process.env.LEG_HOME = HOME0
process.env.BATON_HOME = HOME0
process.env.LEG_HARNESS_HOME = HOME0
const h = await import('../src/harness/index.mjs')
const { createSession, readSession, readEvents, updateSession, appendEvent } = await import('../src/sessions.mjs')
const { sessionDetail } = await import('../src/session-detail.mjs')

function fresh({ claude = true, codex = true, agy = false } = {}) {
  const dir = makeHome()
  process.env.LEG_HOME = join(dir, 'leg'); process.env.BATON_HOME = process.env.LEG_HOME; process.env.LEG_HARNESS_HOME = dir
  if (claude) buildClaudeHome(dir)
  if (codex) buildCodexHome(dir)
  if (agy) buildAgyHome(dir)
  return dir
}
const agentsMd = (dir) => join(dir, '.codex', 'AGENTS.md')
const configToml = (dir) => join(dir, '.codex', 'config.toml')
const stripRegions = (t) => t.replace(/# >>> leg harness [\s\S]*?# <<< leg harness [a-z]+ end\n?/g, '')

test('off (the default): a hand-off records nothing and writes nothing anywhere', () => {
  const dir = fresh()
  const before = { agents: readFileSync(agentsMd(dir), 'utf8'), toml: readFileSync(configToml(dir), 'utf8') }
  const p = h.prepareHarnessForHandoff({ from: 'claude', to: 'codex', sessionId: 's-off' })
  assert.equal(p.state, 'off'); assert.equal(p.proceed, true)
  assert.equal(readFileSync(agentsMd(dir), 'utf8'), before.agents)
  assert.equal(readFileSync(configToml(dir), 'utf8'), before.toml)
  assert.ok(!existsSync(join(process.env.LEG_HOME, 'harness')), 'no harness state directory appears')
  assert.equal(h.getHarnessStatus().policy, 'off')
})

test('warn: the destination is checked and reported stale, nothing is written, the hand-off proceeds', () => {
  const dir = fresh()
  h.setHarnessConfig({ enabled: true, policy: 'warn', source: 'claude' })
  const before = readFileSync(agentsMd(dir), 'utf8')
  const p = h.prepareHarnessForHandoff({ from: 'claude', to: 'codex', sessionId: 's-warn' })
  assert.equal(p.state, 'stale'); assert.equal(p.proceed, true); assert.equal(p.mode, 'check')
  assert.equal(p.files_written, 0)
  assert.equal(readFileSync(agentsMd(dir), 'utf8'), before, 'warn never writes')
  assert.equal(p.components.rules.state, 'stale')
  assert.match(p.summary, /warn policy: not synced/)
  assert.ok(existsSync(join(process.env.LEG_HOME, 'harness', 'bundle', 'manifest.json')), 'the capture itself happened')
})

test('sync: the destination is written with managed regions only; user content, user hooks and user MCP servers survive byte for byte; a second hand-off writes nothing', () => {
  const dir = fresh()
  h.setHarnessConfig({ enabled: true, policy: 'sync', source: 'claude' })
  const tomlBefore = readFileSync(configToml(dir), 'utf8')
  const p = h.prepareHarnessForHandoff({ from: 'claude', to: 'codex', sessionId: 's-sync' })
  assert.equal(p.proceed, true); assert.equal(p.mode, 'sync')
  assert.ok(['synced', 'partial'].includes(p.state), p.summary)
  assert.ok(p.files_written > 0)
  const agents = readFileSync(agentsMd(dir), 'utf8')
  assert.ok(agents.split('\n').slice(0, 5).some((l) => l.includes('GENERATED by Leg harness')), 'ownership claim in the head')
  assert.match(agents, /Batch tool calls/)
  assert.match(agents, /Never commit secrets/)
  assert.match(agents, /Direct, no filler/, 'identity inlined')
  assert.ok(!agents.includes('agnostic-ai'), 'no engine branding leaks into a user file')
  const toml = readFileSync(configToml(dir), 'utf8')
  assert.equal(stripRegions(toml).replace(/\n{2,}/g, '\n').trim(), stripRegions(tomlBefore).replace(/\n{2,}/g, '\n').trim(), 'outside the managed regions config.toml is untouched')
  assert.match(toml, /\[mcp_servers\.existing\]/)
  assert.match(toml, /codex-guard/)
  assert.match(toml, /\[mcp_servers\.docs\]/)
  assert.match(toml, /env_vars = \["CONTEXT7_API_KEY"\]/, 'the credential is a reference, not a value')
  assert.ok(!toml.includes(fakeToken('a')) && !toml.includes(CANARY.claude))
  assert.match(toml, /trusted_hash = "sha256:/, 'ported hooks are pre-trusted')
  assert.equal(lstatSync(join(dir, '.codex', 'skills', 'alpha')).isSymbolicLink(), true, 'skills are linked, not copied')
  assert.equal(lstatSync(join(dir, '.codex', 'skills', 'beta')).isSymbolicLink(), false, 'the real beta dir was left alone')
  assert.ok(p.dropped.some((d) => d.component === 'skills' && /beta/.test(d.item)))
  assert.ok(existsSync(join(dir, '.codex', 'prompts', 'wrap.md')))
  assert.ok(existsSync(join(dir, '.codex', 'agents', 'opus-owner.toml')))
  // idempotent
  const p2 = h.prepareHarnessForHandoff({ from: 'claude', to: 'codex', sessionId: 's-sync' })
  assert.equal(p2.mode, 'check'); assert.equal(p2.files_written, 0)
  assert.equal(p2.capture_cached, true)
  assert.equal(readFileSync(configToml(dir), 'utf8'), toml)
  const rows = h.readHistory().filter((r) => r.session_id === 's-sync')
  assert.ok(rows.some((r) => r.op === 'apply' && r.target === 'codex' && r.written > 0))
  assert.ok(rows.every((r) => JSON.stringify(r).includes(fakeToken('a')) === false))
})

test('sync: a source change is noticed at the next hand-off and only the affected managed state changes', () => {
  const dir = fresh()
  h.setHarnessConfig({ enabled: true, policy: 'sync', source: 'claude' })
  h.prepareHarnessForHandoff({ from: 'claude', to: 'codex' })
  const tomlBefore = readFileSync(configToml(dir), 'utf8')
  const promptBefore = readFileSync(join(dir, '.codex', 'prompts', 'wrap.md'), 'utf8')
  writeFileSync(join(dir, '.claude', 'CLAUDE.md'), readFileSync(join(dir, '.claude', 'CLAUDE.md'), 'utf8') + '\n- A brand new rule added mid-session.\n')
  assert.equal(h.getHarnessStatus().source_changed, true)
  const p = h.prepareHarnessForHandoff({ from: 'claude', to: 'codex' })
  assert.equal(p.capture_cached, false); assert.equal(p.mode, 'sync')
  assert.match(readFileSync(agentsMd(dir), 'utf8'), /brand new rule added mid-session/)
  assert.equal(readFileSync(configToml(dir), 'utf8'), tomlBefore, 'hooks and MCP were not rewritten')
  assert.equal(readFileSync(join(dir, '.codex', 'prompts', 'wrap.md'), 'utf8'), promptBefore)
  assert.equal(p.files_written, 1, 'exactly the rules file changed')
})

test('a hand-edited managed file is backed up and left alone: sync reports attention and proceeds, strict refuses', () => {
  const dir = fresh()
  h.setHarnessConfig({ enabled: true, policy: 'sync', source: 'claude' })
  h.prepareHarnessForHandoff({ from: 'claude', to: 'codex' })
  const edited = readFileSync(agentsMd(dir), 'utf8').split('\n').filter((l) => !l.includes('GENERATED by Leg harness')).join('\n') + '\nMy own line.\n'
  writeFileSync(agentsMd(dir), edited)
  const p = h.prepareHarnessForHandoff({ from: 'claude', to: 'codex', sessionId: 's-edit' })
  assert.equal(p.state, 'attention'); assert.equal(p.proceed, true)
  assert.equal(readFileSync(agentsMd(dir), 'utf8'), edited, 'the hand edit survives')
  assert.ok(p.attention.some((a) => a.component === 'rules' && /hand-edited/.test(a.reason)))
  const backups = readdirSync(join(process.env.LEG_HOME, 'harness', 'backups'))
  assert.ok(backups.some((n) => n.startsWith('codex-AGENTS.md')), `a backup exists: ${backups.join(', ')}`)
  // two backups by now: the fixture's original from the first write, and the hand-edited text from the refusal
  assert.ok(backups.filter((n) => n.startsWith('codex-AGENTS.md')).some((n) => readFileSync(join(process.env.LEG_HOME, 'harness', 'backups', n), 'utf8').includes('My own line.')), 'the hand-edited text was backed up')
  h.setHarnessConfig({ policy: 'strict' })
  const s = h.prepareHarnessForHandoff({ from: 'claude', to: 'codex', sessionId: 's-strict' })
  assert.equal(s.state, 'blocked'); assert.equal(s.proceed, false)
  assert.match(s.reason, /strict policy: codex is attention/)
  assert.equal(readFileSync(agentsMd(dir), 'utf8'), edited, 'strict never forces')
  // --force replaces it; the hand-edited text was backed up once, at first detection, and that backup is what survives the overwrite
  const forced = h.applyHarness({ to: 'codex', force: true })
  assert.equal(forced.targets.codex.files_written, 1)
  const kept = readdirSync(join(process.env.LEG_HOME, 'harness', 'backups')).filter((n) => n.startsWith('codex-AGENTS.md')).map((n) => readFileSync(join(process.env.LEG_HOME, 'harness', 'backups', n), 'utf8'))
  assert.ok(kept.some((t) => t.includes('My own line.')), 'the overwritten hand edit is recoverable from a backup')
  assert.match(readFileSync(agentsMd(dir), 'utf8'), /GENERATED by Leg harness/)
  const s2 = h.prepareHarnessForHandoff({ from: 'claude', to: 'codex', sessionId: 's-strict2' })
  assert.equal(s2.proceed, true)
  assert.ok(h.readHistory().some((r) => r.op === 'prepare' && r.session_id === 's-strict' && r.proceed === false))
})

test('strict: an unsupported destination (grok, or a client not installed) is refused; warn and sync only note it', () => {
  fresh({ codex: false })
  h.setHarnessConfig({ enabled: true, policy: 'strict', source: 'claude' })
  const g = h.prepareHarnessForHandoff({ from: 'claude', to: 'grok' })
  assert.equal(g.state, 'unsupported'); assert.equal(g.proceed, false)
  const c = h.prepareHarnessForHandoff({ from: 'claude', to: 'codex' })
  assert.equal(c.state, 'unsupported'); assert.equal(c.proceed, false)
  assert.match(c.reason, /not installed/)
  h.setHarnessConfig({ policy: 'sync' })
  assert.equal(h.prepareHarnessForHandoff({ from: 'claude', to: 'grok' }).proceed, true)
  assert.equal(h.prepareHarnessForHandoff({ from: 'claude', to: 'codex' }).proceed, true)
})

test('the destination that is the source, and a same-client hand-off (another login), are never written', () => {
  const dir = fresh()
  h.setHarnessConfig({ enabled: true, policy: 'strict', source: 'claude' })
  const before = readFileSync(join(dir, '.claude', 'CLAUDE.md'), 'utf8')
  const src = h.prepareHarnessForHandoff({ from: 'codex', to: 'claude' })
  assert.equal(src.state, 'source'); assert.equal(src.proceed, true)
  const same = h.prepareHarnessForHandoff({ from: 'codex', to: 'codex' })
  assert.equal(same.state, 'same-client'); assert.equal(same.proceed, true)
  const fake = h.prepareHarnessForHandoff({ from: 'fake-claude', to: 'fake-claude' })
  assert.equal(fake.state, 'same-client')
  assert.equal(readFileSync(join(dir, '.claude', 'CLAUDE.md'), 'utf8'), before)
  assert.ok(!existsSync(join(dir, '.claude', 'leg-rules.md')), 'the source client never receives its own harness')
})

test('codex as the source, claude as the destination: CLAUDE.md gains one import line and keeps its content; settings.json keeps foreign hooks', () => {
  const dir = fresh({ claude: false })
  mkdirSync(join(dir, '.claude'), { recursive: true })
  writeFileSync(join(dir, '.claude', 'CLAUDE.md'), '# CLAUDE.md\n\nMy hand-written instructions.\n')
  writeFileSync(join(dir, '.claude', 'settings.json'), JSON.stringify({ hooks: { PreToolUse: [{ matcher: 'foreign', hooks: [{ type: 'command', command: 'node foreign.cjs' }] }] } }, null, 2))
  h.setHarnessConfig({ enabled: true, policy: 'sync', source: 'codex' })
  const p = h.prepareHarnessForHandoff({ from: 'codex', to: 'claude', sessionId: 's-rev' })
  assert.ok(['synced', 'partial'].includes(p.state), p.summary)
  const md = readFileSync(join(dir, '.claude', 'CLAUDE.md'), 'utf8')
  assert.match(md, /My hand-written instructions\./)
  assert.equal(md.split('@~/.claude/leg-rules.md').length - 1, 1, 'exactly one import line')
  assert.match(readFileSync(join(dir, '.claude', 'leg-rules.md'), 'utf8'), /Keep diffs minimal/)
  const settings = JSON.parse(readFileSync(join(dir, '.claude', 'settings.json'), 'utf8'))
  assert.ok(settings.hooks.PreToolUse.some((g) => g.matcher === 'foreign'))
  assert.ok(settings.hooks.PreToolUse.length > 1, 'the ported group sits beside the foreign one')
  assert.ok(!readFileSync(join(dir, '.claude', 'settings.json'), 'utf8').includes(CANARY.codex))
  const p2 = h.prepareHarnessForHandoff({ from: 'codex', to: 'claude' })
  assert.equal(p2.files_written, 0)
  assert.equal(readFileSync(join(dir, '.claude', 'CLAUDE.md'), 'utf8'), md)
})

test('agy as the destination: hooks land under one owned key beside another plugin, GEMINI.md is written, unsupported events are dropped with reasons', () => {
  const dir = fresh({ agy: true })
  h.setHarnessConfig({ enabled: true, policy: 'sync', source: 'claude' })
  const p = h.prepareHarnessForHandoff({ from: 'claude', to: 'agy', sessionId: 's-agy' })
  assert.ok(['synced', 'partial'].includes(p.state), p.summary)
  const hooks = JSON.parse(readFileSync(join(dir, '.gemini', 'config', 'hooks.json'), 'utf8'))
  assert.ok(hooks['other-plugin'], 'the other plugin keeps its key')
  assert.ok(hooks[h.BRAND.id], 'Leg owns exactly its own key')
  assert.match(JSON.stringify(hooks[h.BRAND.id]), /shim\.cjs/)
  assert.match(readFileSync(join(dir, '.gemini', 'GEMINI.md'), 'utf8'), /Batch tool calls/)
  assert.ok(p.dropped.some((d) => d.component === 'hooks' && /SessionStart/.test(d.item) && /Antigravity/.test(d.reason)))
  assert.equal(p.components.permissions.state, 'unsupported')
  assert.equal(p.components.agents.state, 'synced')
})

test('ownership: a skill removed at the source is unlinked at the destination; a real directory with the same name is never touched', () => {
  const dir = fresh()
  h.setHarnessConfig({ enabled: true, policy: 'sync', source: 'claude' })
  h.prepareHarnessForHandoff({ from: 'claude', to: 'codex' })
  assert.ok(lstatSync(join(dir, '.codex', 'skills', 'alpha')).isSymbolicLink())
  rmSync(join(dir, '.claude', 'skills', 'alpha'), { recursive: true, force: true })
  const p = h.prepareHarnessForHandoff({ from: 'claude', to: 'codex' })
  assert.equal(p.mode, 'sync')
  assert.ok(!existsSync(join(dir, '.codex', 'skills', 'alpha')), 'the dangling link was pruned')
  assert.ok(existsSync(join(dir, '.codex', 'skills', 'beta', 'SKILL.md')), 'the user\'s real beta dir survives')
  assert.match(readFileSync(join(dir, '.codex', 'skills', 'beta', 'SKILL.md'), 'utf8'), /the Codex way/)
})

test('a generated file pruned because its source went away is backed up first', () => {
  const dir = fresh()
  h.setHarnessConfig({ enabled: true, policy: 'sync', source: 'claude' })
  h.prepareHarnessForHandoff({ from: 'claude', to: 'codex' })
  const advisor = join(dir, '.codex', 'agents', 'advisor.toml')
  assert.ok(existsSync(advisor))
  // the user edits the generated file, then the source agent is deleted
  writeFileSync(advisor, readFileSync(advisor, 'utf8') + '\n# my local tweak\n')
  rmSync(join(dir, '.claude', 'agents', 'advisor.md'))
  h.prepareHarnessForHandoff({ from: 'claude', to: 'codex' })
  assert.ok(!existsSync(advisor), 'pruned')
  const backups = readdirSync(join(process.env.LEG_HOME, 'harness', 'backups')).filter((n) => n.startsWith('codex-advisor.toml'))
  assert.ok(backups.length >= 1, 'a backup was taken before the prune')
  assert.ok(backups.some((n) => readFileSync(join(process.env.LEG_HOME, 'harness', 'backups', n), 'utf8').includes('my local tweak')), 'and it holds the edited content')
})

test('a deny or ask the destination cannot express is attention, never a silent widening: sync proceeds and says so, strict refuses', () => {
  const dir = fresh()
  const settings = JSON.parse(readFileSync(join(dir, '.claude', 'settings.json'), 'utf8'))
  settings.permissions.deny.push('Read(~/.ssh/**)')
  writeFileSync(join(dir, '.claude', 'settings.json'), JSON.stringify(settings, null, 2))
  h.setHarnessConfig({ enabled: true, policy: 'sync', source: 'claude' })
  const p = h.prepareHarnessForHandoff({ from: 'claude', to: 'codex' })
  assert.equal(p.state, 'attention'); assert.equal(p.proceed, true)
  assert.ok(p.attention.some((a) => a.component === 'permissions' && /deny: Read\(~\/\.ssh/.test(a.reason) && /less restricted/.test(a.reason)), JSON.stringify(p.attention))
  h.setHarnessConfig({ policy: 'strict' })
  assert.equal(h.prepareHarnessForHandoff({ from: 'claude', to: 'codex' }).proceed, false)
})

test('a sync writes under the client homes only: a checkout with its own instruction files is byte-identical afterwards', () => {
  const dir = fresh()
  const repo = join(dir, 'checkout')
  mkdirSync(repo, { recursive: true })
  writeFileSync(join(repo, 'CLAUDE.md'), '# project rules\n\n- repo-local.\n')
  writeFileSync(join(repo, 'AGENTS.md'), '# project agents\n')
  const before = Object.fromEntries(readdirSync(repo).map((n) => [n, readFileSync(join(repo, n), 'utf8')]))
  const cwd = process.cwd()
  process.chdir(repo)
  try {
    h.setHarnessConfig({ enabled: true, policy: 'sync', source: 'claude' })
    h.prepareHarnessForHandoff({ from: 'claude', to: 'codex' })
    h.applyHarness()
  } finally { process.chdir(cwd) }
  assert.deepEqual(Object.fromEntries(readdirSync(repo).map((n) => [n, readFileSync(join(repo, n), 'utf8')])), before)
})

test('the board may narrow the harness policy or turn it off, never widen it or turn it on', async () => {
  fresh()
  h.setHarnessConfig({ enabled: true, policy: 'warn', source: 'claude' })
  const { createBoardServer } = await import('../src/server.mjs')
  const server = createBoardServer({ bind: '127.0.0.1', port: 0, token: '', scheduler: false })
  const { port } = await server.start()
  const post = async (body) => { const r = await fetch(`http://127.0.0.1:${port}/api/settings`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }); return { status: r.status, json: await r.json() } }
  try {
    assert.equal((await post({ harness: { policy: 'sync' } })).status, 400, 'warn -> sync is a widening')
    assert.equal((await post({ harness: { policy: 'strict' } })).status, 400)
    assert.equal((await post({ harness: { enabled: true } })).status, 400)
    assert.equal(h.harnessConfig().policy, 'warn')
    h.setHarnessConfig({ policy: 'strict' })
    const narrowed = await post({ harness: { policy: 'sync' } })
    assert.equal(narrowed.status, 200); assert.equal(narrowed.json.preferences.harness.policy, 'sync')
    const off = await post({ harness: { enabled: false } })
    assert.equal(off.status, 200); assert.equal(off.json.preferences.harness.enabled, false)
  } finally { await server.stop() }
})

test('disable: files Leg wrote stay in place, later hand-offs record nothing, and status says off', () => {
  const dir = fresh()
  h.setHarnessConfig({ enabled: true, policy: 'sync', source: 'claude' })
  h.prepareHarnessForHandoff({ from: 'claude', to: 'codex' })
  const agents = readFileSync(agentsMd(dir), 'utf8')
  h.setHarnessConfig({ enabled: false })
  const p = h.prepareHarnessForHandoff({ from: 'claude', to: 'codex' })
  assert.equal(p.state, 'off')
  assert.equal(readFileSync(agentsMd(dir), 'utf8'), agents)
  assert.match(readFileSync(configToml(dir), 'utf8'), /\[mcp_servers\.existing\]/)
  assert.equal(h.getHarnessStatus().enabled, false)
})

test('the session record and the drawer payload carry the outcome: source, capture time, components, dropped items, attention, and the trail', () => {
  const dir = fresh()
  h.setHarnessConfig({ enabled: true, policy: 'sync', source: 'claude' })
  const s = createSession({ id: 's-detail-1', agent: 'codex', cwd: dir })
  assert.equal(s.harness, null, 'a fresh session has no harness outcome yet')
  const outcome = h.prepareHarnessForHandoff({ from: 'claude', to: 'codex', sessionId: s.session_id })
  updateSession(s.session_id, { harness: outcome, lineage: { from: 'claude', to: 'codex' } })
  appendEvent(s.session_id, { type: 'harness', summary: outcome.summary })
  const d = sessionDetail(readSession(s.session_id))
  assert.equal(d.harness.source, 'claude')
  assert.equal(d.harness.target, 'codex')
  assert.ok(d.harness.captured_at)
  assert.ok(['synced', 'partial'].includes(d.harness.state))
  assert.equal(d.harness.components.rules.state, 'synced')
  assert.equal(d.harness.components.skills.total, 3)
  assert.equal(d.harness.components.skills.carried, 2)
  assert.ok(d.harness.dropped.every((x) => x.reason && x.component))
  assert.ok(d.harness.history.some((r) => r.op === 'apply' && r.target === 'codex'))
  assert.ok(readEvents(s.session_id).some((e) => e.type === 'harness'))
  assert.ok(!JSON.stringify(d).includes(fakeToken('a')))
})

test('the port policy file narrows what is carried and the drop is marked as intentional', () => {
  const dir = fresh()
  h.setHarnessConfig({ enabled: true, policy: 'sync', source: 'claude' })
  mkdirSync(join(process.env.LEG_HOME, 'harness'), { recursive: true })
  writeFileSync(join(process.env.LEG_HOME, 'harness', 'policy.json'), JSON.stringify({ skills: { exclude: { gamma: 'browser-only skill; Codex has no browser tool' } }, mcp: { exclude: { remote: 'per-client login' } } }))
  const p = h.prepareHarnessForHandoff({ from: 'claude', to: 'codex' })
  const gamma = p.dropped.find((d) => /gamma/.test(d.item))
  assert.ok(gamma && gamma.excluded === true, JSON.stringify(p.dropped))
  assert.match(gamma.reason, /browser-only/)
  assert.ok(!existsSync(join(dir, '.codex', 'skills', 'gamma')))
  assert.ok(!readFileSync(configToml(dir), 'utf8').includes('[mcp_servers.remote]'))
  assert.equal(p.state, 'partial', 'other, unintentional drops still make it partial')
})

test('failure model: an unreadable destination config is an error that never blocks a sync-policy hand-off and writes nothing', () => {
  const dir = fresh()
  mkdirSync(join(dir, '.gemini'), { recursive: true })
  writeFileSync(join(dir, '.gemini', 'settings.json'), '{ this is not json')
  h.setHarnessConfig({ enabled: true, policy: 'sync', source: 'claude' })
  const p = h.prepareHarnessForHandoff({ from: 'claude', to: 'gemini' })
  assert.equal(p.proceed, true)
  assert.ok(['attention', 'error'].includes(p.state), p.summary)
  assert.ok(p.attention.some((a) => /not valid JSON/.test(a.reason)))
  assert.equal(readFileSync(join(dir, '.gemini', 'settings.json'), 'utf8'), '{ this is not json', 'a malformed file is never rewritten')
  h.setHarnessConfig({ policy: 'strict' })
  assert.equal(h.prepareHarnessForHandoff({ from: 'claude', to: 'gemini' }).proceed, false)
})
