// registry — which coding clients Leg can carry a harness between, and where
// each keeps its configuration. Built from the engine's own client registry
// (src/harness/vendor/agnostic-ai/core/templates/targets.json, byte-for-byte
// from upstream) narrowed to the clients Leg launches and given Leg's own
// generated-file preambles. Paths honour the same config-dir variables the
// trust module and the account layer honour (CLAUDE_CONFIG_DIR, CODEX_HOME,
// GEMINI_CONFIG_DIR), so a harness lands where the agent Leg starts will read.
import { existsSync, readFileSync } from 'node:fs'
import { homedir } from 'node:os'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import engine from './vendor/agnostic-ai/engine/harness/index.cjs'

const HERE = dirname(fileURLToPath(import.meta.url))
export const VENDOR = join(HERE, 'vendor', 'agnostic-ai')
const TARGETS_FILE = join(VENDOR, 'core', 'templates', 'targets.json')

// The clients a `leg <agent>` session can hand off between, plus Gemini CLI,
// which shares GEMINI.md with Antigravity and is kept coherent with it.
export const CLIENT_IDS = ['claude', 'codex', 'gemini', 'agy']
// Clients the engine can read a harness FROM.
export const SOURCE_IDS = ['claude', 'codex']
// Leg agents with no harness adapter: reported as unsupported, never guessed.
export const NO_ADAPTER = { grok: 'the Grok CLI has no harness adapter yet: its rules, skills and MCP servers are not carried' }

export const BRAND = Object.freeze({ id: 'leg-harness', mark: 'GENERATED by Leg harness', region: 'leg harness' })

const PATH_FIELDS = ['home', 'rulesFile', 'traitsFile', 'hooksConfigFile', 'skillsDir', 'agentsDir', 'commandsDir', 'mcpConfigFile', 'permissionsFile']

// Leg's own preamble per client: the ownership claim (BRAND.mark) in the first
// lines, and the command that regenerates the file.
const PREAMBLES = {
  claude: '# Leg harness rules (Claude Code)\n\nGENERATED by Leg harness from the captured source client. Do not hand-edit; edit the source client and run `leg harness sync`. Loaded via an @import line in ~/.claude/CLAUDE.md.\n',
  codex: '# AGENTS.md (Codex CLI)\n\nGENERATED by Leg harness from the captured source client. Do not hand-edit; edit the source client and run `leg harness sync`.\n',
  gemini: '# GEMINI.md (Gemini CLI)\n\nGENERATED by Leg harness from the captured source client. Do not hand-edit; edit the source client and run `leg harness sync`.\n',
  agy: '# GEMINI.md (Gemini CLI)\n\nGENERATED by Leg harness from the captured source client. Do not hand-edit; edit the source client and run `leg harness sync`.\n',
}

// Leg writes its rules file under its own name so it never collides with a
// file another tool generated into the same client.
const RENAMES = {
  claude: { rulesFile: '~/.claude/leg-rules.md' },
  codex: { permissionsFile: '~/.codex/rules/leg-harness.rules' },
}

// A drive-letter path is absolute on every host (src/trust.mjs makes the same call).
const DRIVE_ABS = /^[A-Za-z]:[\\/]/
const absolutely = (p) => (DRIVE_ABS.test(p) ? p : resolve(p))

// `~/.codex` -> $CODEX_HOME, and so on, applied to every path field of one
// entry. The variable names a directory; the file names inside it stay.
function rebase(entry, from, to) {
  const out = { ...entry }
  for (const field of PATH_FIELDS) {
    const v = entry[field]
    if (typeof v !== 'string') continue
    if (v === from) out[field] = to
    else if (v.startsWith(from + '/')) out[field] = join(to, v.slice(from.length + 1))
  }
  return out
}

function envOverrides(entry, env) {
  let e = entry
  if (entry.id === 'claude' && env.CLAUDE_CONFIG_DIR) {
    const dir = absolutely(env.CLAUDE_CONFIG_DIR)
    e = rebase(e, '~/.claude', dir)
    // Claude Code keeps its MCP servers beside the config dir, not inside it
    if (e.mcpConfigFile === '~/.claude.json') e.mcpConfigFile = join(dir, '.claude.json')
  }
  if (entry.id === 'codex' && env.CODEX_HOME) e = rebase(e, '~/.codex', absolutely(env.CODEX_HOME))
  if ((entry.id === 'gemini' || entry.id === 'agy') && env.GEMINI_CONFIG_DIR) e = rebase(e, '~/.gemini', absolutely(env.GEMINI_CONFIG_DIR))
  return e
}

// The OS home the client registry expands `~/` against. LEG_HARNESS_HOME is
// the test seam: the suite points it at a throwaway directory so nothing it
// does can reach the developer's real ~/.claude, ~/.codex or ~/.gemini.
export function harnessHome(env = process.env) {
  const v = env.LEG_HARNESS_HOME || env.BATON_HARNESS_HOME
  return v ? absolutely(v) : homedir()
}

let rawCache = null
function rawTargets() {
  if (!rawCache) rawCache = JSON.parse(readFileSync(TARGETS_FILE, 'utf8')).targets
  return rawCache
}

// The expanded registry: one entry per client, `installed` read from disk.
export function registry({ env = process.env, home = harnessHome(env) } = {}) {
  const targets = rawTargets()
    .filter((t) => CLIENT_IDS.includes(t.id))
    .map((t) => ({ ...t, ...(RENAMES[t.id] ?? {}), preamble: PREAMBLES[t.id] ?? t.preamble }))
    .map((t) => envOverrides(t, env))
  return engine.loadRegistry(home, { targets })
}

export function targetFor(id, opts) {
  return registry(opts).find((t) => t.id === id) ?? null
}

// A Leg adapter name -> the client whose harness it runs under. Fake adapters
// emulate a real client (bin/fake-agent.mjs); the plain `fake` emulates none.
export function clientFor(adapter) {
  if (!adapter) return null
  const name = String(adapter).replace(/^fake-/, '')
  if (name === 'fake') return null
  return name
}

// Which sources exist on this machine, decided from disk: the rules file a
// user of that client necessarily has.
export function detectSources({ env = process.env, home = harnessHome(env) } = {}) {
  const reg = registry({ env, home })
  const out = []
  for (const id of SOURCE_IDS) {
    const t = reg.find((x) => x.id === id)
    if (!t) continue
    const rulesFile = id === 'claude' ? join(t.home, 'CLAUDE.md') : t.rulesFile
    if (existsSync(rulesFile)) out.push({ id, home: t.home, rulesFile })
  }
  return out
}
