#!/usr/bin/env node
// limits-table — regenerate the Limit signals table in docs/cli-contracts.md
// from fixtures/limits/**/*.json (the same files src/limits.mjs classifies with).
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { SIGNALS } from '../src/limits.mjs'

const DOC = resolve(dirname(fileURLToPath(import.meta.url)), '..', 'docs', 'cli-contracts.md')
const START = '<!-- limits-table:start -->'
const END = '<!-- limits-table:end -->'

const cell = (s) => String(s).replace(/\|/g, '\\|').replace(/\r?\n/g, ' ')
const rows = SIGNALS.map((s) =>
  `| ${s.id} | ${s.adapter} | ${s.classification} | ${s.where} | **${s.source}** | ${cell(s.text).slice(0, 90)} | ${cell(s.produced_by)} |`)
const counts = SIGNALS.reduce((m, s) => { m[s.source] = (m[s.source] ?? 0) + 1; return m }, {})
const table = [
  `Generated by \`node scripts/limits-table.mjs\` from ${SIGNALS.length} fixtures (${counts['observed-live'] ?? 0} observed-live, ${counts['docs-only'] ?? 0} docs-only). Classification \`limit\` hands the card to the next agent as a usage limit; \`auth\` is a failed launch (never a limit); \`launch\` is a failed launch that the next agent may still try; \`budget\` is a turn or spend cap set by Baton itself; \`info\` must never classify as a limit.`,
  '',
  '| id | adapter | class | where | source | text (excerpt) | produced by |',
  '|----|---------|-------|-------|--------|----------------|-------------|',
  ...rows,
].join('\n')

const doc = readFileSync(DOC, 'utf8')
const a = doc.indexOf(START)
const b = doc.indexOf(END)
if (a === -1 || b === -1 || b < a) {
  process.stderr.write(`markers ${START} / ${END} not found in ${DOC}\n`)
  process.exit(1)
}
const next = doc.slice(0, a + START.length) + '\n' + table + '\n' + doc.slice(b)
if (process.argv.includes('--check')) {
  process.stdout.write(next === doc ? 'limits-table: up to date\n' : 'limits-table: STALE (run node scripts/limits-table.mjs)\n')
  process.exit(next === doc ? 0 : 1)
}
writeFileSync(DOC, next)
process.stdout.write(`limits-table: wrote ${SIGNALS.length} rows into ${DOC}\n`)
